"""
Riverside Security Requirements Definition.

This module contains the complete catalog of 72 Riverside security requirements
organized into 8 categories with maturity levels, phases, and target dates.
"""

from .riverside_models import (
    PHASE_1_TARGET_DATE,
    PHASE_2_TARGET_DATE,
    PHASE_3_TARGET_DATE,
    DeadlinePhase,
    RequirementLevel,
    RiversideRequirement,
    RiversideRequirementCategory,
)

# 72 Riverside Security Requirements
REQUIREMENTS: list[RiversideRequirement] = [
    RiversideRequirement(
        id="MFA-001",
        category=RiversideRequirementCategory.MFA_ENFORCEMENT,
        title="Enforce MFA for all tenant administrators",
        description="Multi-factor authentication must be enforced for all users with administrative roles to prevent unauthorized access",
        control_source="NIST 800-171",
        control_reference="3.5.3",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="MFA-002",
        category=RiversideRequirementCategory.MFA_ENFORCEMENT,
        title="Enable per-user MFA for privileged roles",
        description="Enable MFA for users with privileged access rights including Security Admin, Exchange Admin, and SharePoint Admin roles",
        control_source="CIS Microsoft 365",
        control_reference="1.1.1",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="MFA-003",
        category=RiversideRequirementCategory.MFA_ENFORCEMENT,
        title="Disable MFA registration bypass",
        description="Disable the ability for users to bypass MFA registration during sign-in to ensure full coverage",
        control_source="Microsoft Security Baseline",
        control_reference="MFA-002",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="MFA-004",
        category=RiversideRequirementCategory.MFA_ENFORCEMENT,
        title="Deploy Microsoft Authenticator passwordless",
        description="Deploy Microsoft Authenticator app for passwordless sign-in to reduce password-based attack surface",
        control_source="Zero Trust Guidance",
        control_reference="ZT-101",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="MFA-005",
        category=RiversideRequirementCategory.MFA_ENFORCEMENT,
        title="Require MFA for device enrollment",
        description="Enforce MFA requirement before allowing devices to enroll in mobile device management",
        control_source="Entra ID",
        control_reference="Conditional Access",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="MFA-006",
        category=RiversideRequirementCategory.MFA_ENFORCEMENT,
        title="Enforce risk-based MFA triggers",
        description="Configure risk-based conditional access policies to require MFA based on sign-in risk levels",
        control_source="Identity Protection",
        control_reference="Risk Policy",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="MFA-007",
        category=RiversideRequirementCategory.MFA_ENFORCEMENT,
        title="Implement number matching for MFA",
        description="Enable number matching feature in MFA prompts to prevent MFA fatigue attacks",
        control_source="Microsoft Authenticator",
        control_reference="Security Features",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="MFA-008",
        category=RiversideRequirementCategory.MFA_ENFORCEMENT,
        title="MFA for third-party federation",
        description="Require MFA for federated identities accessing Microsoft 365 resources via third-party identity providers",
        control_source="Federated Identity",
        control_reference="Federated-Auth",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    RiversideRequirement(
        id="MFA-009",
        category=RiversideRequirementCategory.MFA_ENFORCEMENT,
        title="Passwordless MFA for all users",
        description="Achieve 100% passwordless authentication using FIDO2 keys, Microsoft Authenticator, or Windows Hello for Business",
        control_source="Zero Trust Maturity",
        control_reference="Passwordless",
        maturity_level=RequirementLevel.LEADING,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    # Conditional Access (9)
    RiversideRequirement(
        id="CA-001",
        category=RiversideRequirementCategory.CONDITIONAL_ACCESS,
        title="Block legacy authentication",
        description="Block legacy authentication protocols (SMTP, POP3, IMAP) that cannot support modern authentication",
        control_source="Conditional Access",
        control_reference="Legacy Blocking",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="CA-002",
        category=RiversideRequirementCategory.CONDITIONAL_ACCESS,
        title="Require device compliance for admin sessions",
        description="Require compliant device status for all administrative role sign-ins to privileged consoles and portals",
        control_source="Admin Privileges",
        control_reference="Device Compliance",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="CA-003",
        category=RiversideRequirementCategory.CONDITIONAL_ACCESS,
        title="Geolocation controls for privileged access",
        description="Implement location-based conditional access policies restricting privileged access to approved countries/regions",
        control_source="Location Controls",
        control_reference="Named Locations",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="CA-004",
        category=RiversideRequirementCategory.CONDITIONAL_ACCESS,
        title="Require MFA for cloud app access",
        description="Require MFA for all users accessing Microsoft 365 cloud applications from outside trusted locations",
        control_source="MFA Requirement",
        control_reference="Cloud Access",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="CA-005",
        category=RiversideRequirementCategory.CONDITIONAL_ACCESS,
        title="App-based conditional access policies",
        description="Create specific conditional access policies for high-risk applications (Entra ID, Exchange, SharePoint, Teams)",
        control_source="App Protection",
        control_reference="Target Apps",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="CA-006",
        category=RiversideRequirementCategory.CONDITIONAL_ACCESS,
        title="Session controls for sensitive apps",
        description="Configure session controls including app enforced restrictions, sign-in frequency, and persistent browser sessions",
        control_source="Session Controls",
        control_reference="Sensitive Apps",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="CA-007",
        category=RiversideRequirementCategory.CONDITIONAL_ACCESS,
        title="Impossible travel detection",
        description="Enable Entra ID sign-in risk detection for impossible travel scenarios indicating credential compromise",
        control_source="Identity Protection",
        control_reference="Risk Detection",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="CA-008",
        category=RiversideRequirementCategory.CONDITIONAL_ACCESS,
        title="Device compliance enforcement on BYOD",
        description="Enforce device compliance policies for personally-owned devices accessing corporate data",
        control_source="BYOD Policy",
        control_reference="Personal Devices",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    RiversideRequirement(
        id="CA-009",
        category=RiversideRequirementCategory.CONDITIONAL_ACCESS,
        title="Just-in-time access enforcement",
        description="Implement just-in-time privileged access with auto-expiration and approval workflows",
        control_source="PIM Integration",
        control_reference="JIT Access",
        maturity_level=RequirementLevel.LEADING,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    # Privileged Access (9)
    RiversideRequirement(
        id="PIM-001",
        category=RiversideRequirementCategory.PRIVILEGED_ACCESS,
        title="Entra ID PIM enabled for global admin",
        description="Enable Privileged Identity Management for Global Administrator role with required approvals for activation",
        control_source="Entra ID PIM",
        control_reference="Privileged Roles",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="PIM-002",
        category=RiversideRequirementCategory.PRIVILEGED_ACCESS,
        title="Global admin role assignment limit",
        description="Limit Global Administrator role assignments to maximum of 5 designated accounts across the tenant",
        control_source="Role Assignment",
        control_reference="Admin Limits",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="PIM-003",
        category=RiversideRequirementCategory.PRIVILEGED_ACCESS,
        title="Require approval for role activation",
        description="Configure approval workflow requiring approval from designated approvers for privileged role activation",
        control_source="PIM Approvals",
        control_reference="Activation Flow",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="PIM-004",
        category=RiversideRequirementCategory.PRIVILEGED_ACCESS,
        title="Role activation time limit",
        description="Set privileged role activation limits between 1-4 hours with automatic deactivation upon expiration",
        control_source="PIM Settings",
        control_reference="Time Limits",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="PIM-005",
        category=RiversideRequirementCategory.PRIVILEGED_ACCESS,
        title="Just-in-time access for critical actions",
        description="Implement elevation requirements for just-in-time access to perform critical administrative actions",
        control_source="Elevation Controls",
        control_reference="Critical Actions",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="PIM-006",
        category=RiversideRequirementCategory.PRIVILEGED_ACCESS,
        title="Role access reviewers rotation",
        description="Implement quarterly rotation of role access reviewers to prevent collusion and control concentration",
        control_source="Access Reviews",
        control_reference="Reviewer Rotation",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="PIM-007",
        category=RiversideRequirementCategory.PRIVILEGED_ACCESS,
        title="Emergency access break-glass account",
        description="Maintain secured emergency break-glass accounts with strict access logging for disaster recovery scenarios",
        control_source="Emergency Access",
        control_reference="Break Glass",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="PIM-008",
        category=RiversideRequirementCategory.PRIVILEGED_ACCESS,
        title="Privileged risk alerts automated responses",
        description="Configure automated remediation actions for detected privileged account risks and anomalies",
        control_source="Automated Response",
        control_reference="Risk Alerts",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    RiversideRequirement(
        id="PIM-009",
        category=RiversideRequirementCategory.PRIVILEGED_ACCESS,
        title="Continuous access evaluation for privileged",
        description="Implement continuous access evaluation for privileged sessions with real-time policy enforcement",
        control_source="Continuous Evaluation",
        control_reference="Real-time Enforcement",
        maturity_level=RequirementLevel.LEADING,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    # Device Compliance (9)
    RiversideRequirement(
        id="DC-001",
        category=RiversideRequirementCategory.DEVICE_COMPLIANCE,
        title="Intune device compliance policies",
        description="Deploy comprehensive Intune compliance policies covering OS version, encryption, health, and security settings",
        control_source="Microsoft Intune",
        control_reference="Compliance Policies",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DC-002",
        category=RiversideRequirementCategory.DEVICE_COMPLIANCE,
        title="Blocked non-compliant devices",
        description="Configure conditional access to block devices failing compliance checks from accessing corporate resources",
        control_source="Device Blocking",
        control_reference="Non-compliant Devices",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DC-003",
        category=RiversideRequirementCategory.DEVICE_COMPLIANCE,
        title="Supported OS version enforcement",
        description="Enforce minimum supported OS versions and block devices running unsupported or outdated operating systems",
        control_source="OS Compliance",
        control_reference="Version Requirements",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DC-004",
        category=RiversideRequirementCategory.DEVICE_COMPLIANCE,
        title="Disk encryption enforcement",
        description="Require BitLocker (Windows) or FileVault (Mac) encryption for all managed devices",
        control_source="Encryption Policy",
        control_reference="Data Protection",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DC-005",
        category=RiversideRequirementCategory.DEVICE_COMPLIANCE,
        title="Application allow-list enforcement",
        description="Implement application allow-listing policies blocking unauthorized applications on managed devices",
        control_source="App Control",
        control_reference="Allow-list Policy",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DC-006",
        category=RiversideRequirementCategory.DEVICE_COMPLIANCE,
        title="Compliant BYOD workflow",
        description="Establish workflow for registering and validating personally-owned devices before corporate access",
        control_source="BYOD Management",
        control_reference="Personal Device Flow",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DC-007",
        category=RiversideRequirementCategory.DEVICE_COMPLIANCE,
        title="Device attestation enforcement",
        description="Require device attestation validating compliance posture before granting access to sensitive applications",
        control_source="Attestation Policy",
        control_reference="Device Health",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DC-008",
        category=RiversideRequirementCategory.DEVICE_COMPLIANCE,
        title="Secure boot enforcement",
        description="Require Secure Boot and TPM 2.0 on all Windows devices for enhanced boot-time security",
        control_source="Boot Security",
        control_reference="Secure Boot",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DC-009",
        category=RiversideRequirementCategory.DEVICE_COMPLIANCE,
        title="Zero Trust device health scoring",
        description="Implement dynamic device health scoring influencing access decisions in real-time",
        control_source="Zero Trust Device",
        control_reference="Health Scoring",
        maturity_level=RequirementLevel.LEADING,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    # Threat Management (9)
    RiversideRequirement(
        id="TM-001",
        category=RiversideRequirementCategory.THREAT_MANAGEMENT,
        title="Microsoft Defender for Office 365",
        description="Deploy Defender for Office 365 Plan 2 with advanced threat protection for email and collaboration",
        control_source="Microsoft Defender",
        control_reference="MDO-365",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="TM-002",
        category=RiversideRequirementCategory.THREAT_MANAGEMENT,
        title="Anti-phishing policies",
        description="Configure anti-phishing policies with impersonation protection, spoof intelligence, and user education",
        control_source="Anti-phishing",
        control_reference="Phish Policies",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="TM-003",
        category=RiversideRequirementCategory.THREAT_MANAGEMENT,
        title="Safe Links enabled",
        description="Enable Safe Links protection for email and Office apps with time-of-click protection and URL rewrites",
        control_source="Safe Links",
        control_reference="Link Protection",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="TM-004",
        category=RiversideRequirementCategory.THREAT_MANAGEMENT,
        title="Safe Attachments enabled",
        description="Enable Safe Attachments scanning in detonation environment before delivering email attachments",
        control_source="Safe Attachments",
        control_reference="Attachment Scanning",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="TM-005",
        category=RiversideRequirementCategory.THREAT_MANAGEMENT,
        title="Automated incident response",
        description="Deploy automated incident response playbooks for common attack patterns and threats",
        control_source="AIR Playbooks",
        control_reference="Automation",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="TM-006",
        category=RiversideRequirementCategory.THREAT_MANAGEMENT,
        title="Threat hunting queries",
        description="Implement threat hunting queries in Microsoft Defender to proactively search for threats",
        control_source="Threat Hunting",
        control_reference="Advanced Hunting",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="TM-007",
        category=RiversideRequirementCategory.THREAT_MANAGEMENT,
        title="Simulation-based training",
        description="Implement security awareness through phishing simulations and targeted user training programs",
        control_source="Attack Simulation",
        control_reference="User Training",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="TM-008",
        category=RiversideRequirementCategory.THREAT_MANAGEMENT,
        title="XDR integration",
        description="Integrate Microsoft Defender XDR across endpoint, identity, and cloud for unified security operations",
        control_source="Defender XDR",
        control_reference="Unified Detection",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    RiversideRequirement(
        id="TM-009",
        category=RiversideRequirementCategory.THREAT_MANAGEMENT,
        title="AI-driven threat analytics",
        description="Deploy AI-powered threat analytics for anomaly detection, behavioral analysis, and predictive intelligence",
        control_source="AI Security",
        control_reference="Threat Intelligence",
        maturity_level=RequirementLevel.LEADING,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    # Data Loss Prevention (9)
    RiversideRequirement(
        id="DLP-001",
        category=RiversideRequirementCategory.DATA_LOSS_PREVENTION,
        title="DLP policies for sensitive data",
        description="Create DLP policies protecting PII, PHI, financial documents, and confidential corporate information",
        control_source="Microsoft Purview",
        control_reference="DLP Policies",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DLP-002",
        category=RiversideRequirementCategory.DATA_LOSS_PREVENTION,
        title="Document fingerprinting",
        description="Deploy exact data match (EDM) and document fingerprinting for template-based sensitive data detection",
        control_source="DLP Fingerprinting",
        control_reference="Data Matching",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DLP-003",
        category=RiversideRequirementCategory.DATA_LOSS_PREVENTION,
        title="Automatic classification",
        description="Enable trainable classifiers and automatic labeling for sensitive content across Microsoft 365",
        control_source="Data Classification",
        control_reference="Auto-labeling",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DLP-004",
        category=RiversideRequirementCategory.DATA_LOSS_PREVENTION,
        title="Endpoint DLP deployed",
        description="Deploy Endpoint DLP agents for monitoring and protecting data on Windows, Mac, and Linux devices",
        control_source="Endpoint DLP",
        control_reference="Endpoint Protection",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DLP-005",
        category=RiversideRequirementCategory.DATA_LOSS_PREVENTION,
        title="Cloud app security integration",
        description="Integrate Microsoft Cloud App Security (MCAS) for shadow IT discovery and CASB capabilities",
        control_source="Cloud App Security",
        control_reference="CASB Integration",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DLP-006",
        category=RiversideRequirementCategory.DATA_LOSS_PREVENTION,
        title="Data encryption enforced",
        description="Enforce encryption at rest and in transit for all Microsoft 365 services and customer data",
        control_source="Data Encryption",
        control_reference="Encryption Keys",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DLP-007",
        category=RiversideRequirementCategory.DATA_LOSS_PREVENTION,
        title="Data residency controls",
        description="Configure data residency and multi-geo controls ensuring data storage compliance with regional requirements",
        control_source="Data Residency",
        control_reference="Geo Controls",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DLP-008",
        category=RiversideRequirementCategory.DATA_LOSS_PREVENTION,
        title="Insider risk monitoring",
        description="Deploy insider risk management to monitor for data exfiltration, inappropriate access, and policy violations",
        control_source="Insider Risk",
        control_reference="User Monitoring",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    RiversideRequirement(
        id="DLP-009",
        category=RiversideRequirementCategory.DATA_LOSS_PREVENTION,
        title="Continuous data loss monitoring",
        description="Implement real-time continuous monitoring for data loss risks with automated alerting and containment",
        control_source="Continuous DLP",
        control_reference="Real-time Monitoring",
        maturity_level=RequirementLevel.LEADING,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    # Logging & Monitoring (9)
    RiversideRequirement(
        id="LM-001",
        category=RiversideRequirementCategory.LOGGING_MONITORING,
        title="Unified audit log enabled",
        description="Enable unified audit log recording across all Microsoft 365 services for comprehensive visibility",
        control_source="Compliance Center",
        control_reference="Audit Logging",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="LM-002",
        category=RiversideRequirementCategory.LOGGING_MONITORING,
        title="Log retention 365 days",
        description="Configure 365-day log retention for audit logs meeting regulatory compliance requirements",
        control_source="Log Retention",
        control_reference="Retention Policy",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="LM-003",
        category=RiversideRequirementCategory.LOGGING_MONITORING,
        title="Alert configuration baseline",
        description="Set up baseline alerting for critical security events including admin operations, suspicious sign-ins, and data access",
        control_source="Alert Baseline",
        control_reference="Security Alerts",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="LM-004",
        category=RiversideRequirementCategory.LOGGING_MONITORING,
        title="Sentinel log analytics integration",
        description="Integrate unified logs with Microsoft Sentinel for centralized SIEM collection and analysis",
        control_source="Microsoft Sentinel",
        control_reference="SIEM Ingestion",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="LM-005",
        category=RiversideRequirementCategory.LOGGING_MONITORING,
        title="Custom workbooks deployed",
        description="Deploy custom Azure Monitor workbooks for Riverside compliance dashboards and status tracking",
        control_source="Azure Monitor",
        control_reference="Custom Dashboards",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="LM-006",
        category=RiversideRequirementCategory.LOGGING_MONITORING,
        title="Anomaly detection rules",
        description="Configure Sentinel analytics rules for anomaly detection, behavioral baselines, and threat patterns",
        control_source="Analytics Rules",
        control_reference="Anomaly Detection",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="LM-007",
        category=RiversideRequirementCategory.LOGGING_MONITORING,
        title="SIEM centralization",
        description="Achieve centralized SIEM for monitoring across Microsoft 365, endpoints, network, and cloud services",
        control_source="SIEM Centralization",
        control_reference="Log Consolidation",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="LM-008",
        category=RiversideRequirementCategory.LOGGING_MONITORING,
        title="Automated playbooks",
        description="Deploy Azure Logic Apps and Sentinel automation playbooks for standardized incident response workflows",
        control_source="Automation",
        control_reference="Playbooks",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    RiversideRequirement(
        id="LM-009",
        category=RiversideRequirementCategory.LOGGING_MONITORING,
        title="Advanced hunting KQL queries",
        description="Implement advanced hunting KQL query library for proactive threat investigation and incident response",
        control_source="Advanced Hunting",
        control_reference="KQL Library",
        maturity_level=RequirementLevel.LEADING,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    # Incident Response (9)
    RiversideRequirement(
        id="IR-001",
        category=RiversideRequirementCategory.INCIDENT_RESPONSE,
        title="Incident response playbook",
        description="Document comprehensive incident response playbooks for ransomware, phishing, data breach, and insider threats",
        control_source="NIST CSF",
        control_reference="IR-PL001",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="IR-002",
        category=RiversideRequirementCategory.INCIDENT_RESPONSE,
        title="On-call rotation defined",
        description="Establish on-call rotation schedule with designated security responders for 24/7 incident coverage",
        control_source="Duty Roster",
        control_reference="On-call Schedule",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="IR-003",
        category=RiversideRequirementCategory.INCIDENT_RESPONSE,
        title="Escalation matrix defined",
        description="Document escalation matrix defining notification paths, stakeholders, and SLAs for different severity levels",
        control_source="Escalation Policy",
        control_reference="Response Matrix",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="IR-004",
        category=RiversideRequirementCategory.INCIDENT_RESPONSE,
        title="Communication templates",
        description="Create incident communication templates for internal stakeholders, customers, and regulatory notifications",
        control_source="Communication",
        control_reference="Template Library",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_1_Q3_2025,
        target_date=PHASE_1_TARGET_DATE,
    ),
    RiversideRequirement(
        id="IR-005",
        category=RiversideRequirementCategory.INCIDENT_RESPONSE,
        title="Automated containment actions",
        description="Implement automated incident containment including account suspension, device isolation, and conditional access enforcement",
        control_source="Automated Response",
        control_reference="Containment",
        maturity_level=RequirementLevel.EMERGING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="IR-006",
        category=RiversideRequirementCategory.INCIDENT_RESPONSE,
        title="Forensic data preservation",
        description="Establish procedures for forensic data preservation, evidence collection, and chain of custody",
        control_source="Forensics",
        control_reference="Evidence Collection",
        maturity_level=RequirementLevel.DEVELOPING,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="IR-007",
        category=RiversideRequirementCategory.INCIDENT_RESPONSE,
        title="Post-incident reviews",
        description="Conduct structured post-incident reviews with root cause analysis and remediation tracking",
        control_source="PIR Process",
        control_reference="Incident Review",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_2_Q4_2025,
        target_date=PHASE_2_TARGET_DATE,
    ),
    RiversideRequirement(
        id="IR-008",
        category=RiversideRequirementCategory.INCIDENT_RESPONSE,
        title="Root cause analysis automation",
        description="Implement automated root cause analysis correlation and timeline reconstruction for incident investigation",
        control_source="RCA Automation",
        control_reference="Investigation Tools",
        maturity_level=RequirementLevel.MATURE,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
    RiversideRequirement(
        id="IR-009",
        category=RiversideRequirementCategory.INCIDENT_RESPONSE,
        title="Self-healing automated responses",
        description="Deploy self-healing capabilities for automatic risk mitigation and incident remediation across the environment",
        control_source="Self-healing",
        control_reference="Autonomic Security",
        maturity_level=RequirementLevel.LEADING,
        phase=DeadlinePhase.PHASE_3_Q1_2026,
        target_date=PHASE_3_TARGET_DATE,
    ),
]
