"""Add custom_compliance_rules table for CM-002.

Revision ID: 005
Revises: 004
Create Date: 2026-03-19 00:00:00.000000

Stores tenant-defined JSON Schema compliance rules per ADR-0005.
Idempotent: skips table creation if it already exists (e.g. init_db
ran first and created it via Base.metadata.create_all).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import inspect

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "005"
down_revision: str | None = "004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "custom_compliance_rules"


def upgrade() -> None:
    """Create custom_compliance_rules table if it does not already exist."""
    conn = op.get_bind()
    inspector = inspect(conn)

    if _TABLE in inspector.get_table_names():
        return  # Already exists — nothing to do

    op.create_table(
        _TABLE,
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("category", sa.String(50), nullable=False),
        sa.Column("severity", sa.String(20), nullable=False, server_default="medium"),
        sa.Column("rule_schema", sa.JSON, nullable=False),
        sa.Column("is_enabled", sa.Boolean, nullable=False, server_default="1"),
        sa.Column("created_by", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Single-column indexes (generated by index=True on mapped_column)
    op.create_index("ix_custom_compliance_rules_tenant_id", _TABLE, ["tenant_id"])
    op.create_index("ix_custom_compliance_rules_category", _TABLE, ["category"])

    # Composite indexes from __table_args__
    op.create_index(
        "ix_custom_rules_tenant_category", _TABLE, ["tenant_id", "category"]
    )
    op.create_index(
        "ix_custom_rules_tenant_enabled", _TABLE, ["tenant_id", "is_enabled"]
    )


def downgrade() -> None:
    """Drop custom_compliance_rules table and all its indexes."""
    conn = op.get_bind()
    inspector = inspect(conn)

    if _TABLE not in inspector.get_table_names():
        return

    for idx in [
        "ix_custom_rules_tenant_enabled",
        "ix_custom_rules_tenant_category",
        "ix_custom_compliance_rules_category",
        "ix_custom_compliance_rules_tenant_id",
    ]:
        try:
            op.drop_index(idx, _TABLE)
        except Exception:
            pass

    op.drop_table(_TABLE)
