"""Core module initialization."""

from app.core.app_insights import (
    AppInsightsMiddleware,
    AppInsightsTelemetryClient,
    TelemetryEvent,
    TelemetryEventType,
    init_app_insights,
    telemetry_client,
    track_auth_login_failure,
    track_auth_login_success,
    track_auth_logout,
    track_auth_token_refresh,
    track_budget_alert,
    track_compliance_violation,
    track_cost_anomaly,
    track_dependency,
    track_sync_completed,
    track_sync_failed,
    track_sync_operation,
)
from app.core.azure_sql_pool import (
    AzureSQLRetryContext,
    get_pool_stats,
    is_azure_sql,
    reset_pool,
    with_azure_sql_retry,
)
from app.core.cache import (
    cache_manager,
    cached,
    delete_cached,
    get_cache_ttl,
    get_cached,
    invalidate_on_sync_completion,
    set_cached,
)
from app.core.circuit_breaker import (
    COMPLIANCE_SYNC_BREAKER,
    COST_SYNC_BREAKER,
    DMARC_SYNC_BREAKER,
    GRAPH_API_BREAKER,
    IDENTITY_SYNC_BREAKER,
    RESOURCE_SYNC_BREAKER,
    RIVERSIDE_SYNC_BREAKER,
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitBreakerError,
    CircuitBreakerRegistry,
    CircuitState,
    circuit_breaker,
    circuit_breaker_registry,
)
from app.core.config import Settings, get_settings
from app.core.database import (
    Base,
    batch_query,
    bulk_insert_chunks,
    eager_load_options,
    get_db,
    get_db_bulk_context,
    get_db_context,
    get_db_stats,
    get_db_with_retry,
    init_db,
    query_with_timing,
)
from app.core.monitoring import (
    PerformanceMonitor,
    SyncJobMetrics,
    get_cache_stats,
    get_performance_dashboard,
    performance_monitor,
    reset_metrics,
    track_query,
    track_sync_job,
)
from app.core.notifications import (
    Notification,
    NotificationChannel,
    Severity,
    create_dashboard_url,
    create_retry_url,
    format_sync_alert,
    record_notification_sent,
    send_notification,
    send_teams_notification,
    severity_meets_threshold,
    should_notify,
)
from app.core.rate_limit import (
    AZURE_API_RATE_LIMITS,
    DEFAULT_LIMITS,
    MultiApiRateLimiter,
    RateLimitConfig,
    RateLimitStrategy,
    TokenBucketRateLimiter,
    calculate_backoff,
    extract_retry_after,
    multi_api_limiter,
    rate_limit,
    rate_limiter,
)
from app.core.resilience import (
    ResilienceConfig,
    ResilienceError,
    ResilientAzureClient,
    get_arm_client,
    get_cost_client,
    get_graph_client,
    get_security_client,
    resilient_api_call,
)
from app.core.scheduler import get_scheduler, init_scheduler, trigger_manual_sync
from app.core.security_headers import (
    BalancedSecurityHeadersMiddleware,
    RelaxedSecurityHeadersMiddleware,
    SecurityHeadersConfig,
    SecurityHeadersMiddleware,
    StrictSecurityHeadersMiddleware,
    create_security_middleware,
)
from app.core.tenant_context import (
    DEFAULT_BRAND,
    BrandColors,
    TenantContextMiddleware,
    get_all_brand_palettes,
    get_brand_colors,
    get_brand_colors_by_code,
    get_brand_context_for_request,
    get_brand_css_variables,
    get_template_context,
    get_tenant_brand_from_request,
    register_template_filters,
)

__all__ = [
    # App Insights / Telemetry
    "TelemetryEvent",
    "TelemetryEventType",
    "AppInsightsTelemetryClient",
    "AppInsightsMiddleware",
    "init_app_insights",
    "track_auth_login_failure",
    "track_auth_login_success",
    "track_auth_logout",
    "track_auth_token_refresh",
    "track_budget_alert",
    "track_compliance_violation",
    "track_cost_anomaly",
    "track_dependency",
    "track_sync_completed",
    "track_sync_failed",
    "track_sync_operation",
    "telemetry_client",
    # Config
    "Settings",
    "get_settings",
    # Database
    "Base",
    "get_db",
    "get_db_context",
    "get_db_bulk_context",
    "get_db_with_retry",
    "init_db",
    "eager_load_options",
    "query_with_timing",
    "batch_query",
    "bulk_insert_chunks",
    "get_db_stats",
    "get_pool_stats",
    "reset_pool",
    "with_azure_sql_retry",
    # Azure SQL Pool
    "AzureSQLRetryContext",
    "is_azure_sql",
    # Cache
    "cache_manager",
    "cached",
    "get_cached",
    "set_cached",
    "delete_cached",
    "get_cache_ttl",
    "invalidate_on_sync_completion",
    # Monitoring
    "PerformanceMonitor",
    "SyncJobMetrics",
    "performance_monitor",
    "track_query",
    "track_sync_job",
    "get_performance_dashboard",
    "get_cache_stats",
    "reset_metrics",
    # Rate Limiting
    "RateLimitConfig",
    "RateLimitStrategy",
    "rate_limit",
    "rate_limiter",
    # Token Bucket Rate Limiting
    "TokenBucketRateLimiter",
    "MultiApiRateLimiter",
    "multi_api_limiter",
    "AZURE_API_RATE_LIMITS",
    "DEFAULT_LIMITS",
    "calculate_backoff",
    "extract_retry_after",
    # Circuit Breaker
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitBreakerError",
    "CircuitBreakerRegistry",
    "CircuitState",
    "circuit_breaker",
    "circuit_breaker_registry",
    "COST_SYNC_BREAKER",
    "COMPLIANCE_SYNC_BREAKER",
    "RESOURCE_SYNC_BREAKER",
    "IDENTITY_SYNC_BREAKER",
    "GRAPH_API_BREAKER",
    "RIVERSIDE_SYNC_BREAKER",
    "DMARC_SYNC_BREAKER",
    # Resilience
    "ResilientAzureClient",
    "ResilienceConfig",
    "ResilienceError",
    "resilient_api_call",
    "get_arm_client",
    "get_graph_client",
    "get_cost_client",
    "get_security_client",
    # Scheduler
    "get_scheduler",
    "init_scheduler",
    "trigger_manual_sync",
    # Security Headers
    "SecurityHeadersMiddleware",
    "SecurityHeadersConfig",
    "StrictSecurityHeadersMiddleware",
    "BalancedSecurityHeadersMiddleware",
    "RelaxedSecurityHeadersMiddleware",
    "create_security_middleware",
    # Notifications
    "Notification",
    "NotificationChannel",
    "Severity",
    "should_notify",
    "send_notification",
    "send_teams_notification",
    "format_sync_alert",
    "record_notification_sent",
    "severity_meets_threshold",
    "create_dashboard_url",
    "create_retry_url",
    # Tenant Context
    "BrandColors",
    "DEFAULT_BRAND",
    "TenantContextMiddleware",
    "get_brand_colors",
    "get_brand_colors_by_code",
    "get_all_brand_palettes",
    "get_tenant_brand_from_request",
    "get_brand_css_variables",
    "get_template_context",
    "get_brand_context_for_request",
    "register_template_filters",
]
